language: generic
sudo: false

# Only build for develop and master (and PRs)
branches:
  only:
    - master

os:
  linux

env:
  global:
    - secure: "ifPjMMIP4eV58IF3//zrPpN8hYPrcT9Sfq953yX3Wu3ObQ0r3y7qHCMBwRLqf14SYDSf4siYPm+GTkKW9Gb4jIZzmOJPFOgSJJx6MjtaS+kbzG3uNGpjqOVz9RfGzXlZM1cNkuPZjofq2pBOIIqrE7psWUJiOfDtAkTa+BGMl6Oc8pBCVtVQt0XT1xkg1nejjNNuRvuKnLCyx40SMReDU68ai4Q0PFmIkbf6duMd8zWfR9ITZJYQETRmZn85KiyW0Ax6W9dQgK0O6n3ucId3QIQ5Iim3MyLzp/d/KeLBnO/i3spTvGrlyPGQLKk78nVjZRVaqKaubJpAXWgCGHOF51LRVvdFc73TTvivu0GPiY0FlyKOsY+MHE13+RJHsLXa9aueO0NUw4/2WjwtCkV2LYHJRszc8VbyD6b8mgJwc6lchaptmNknn9TvlCTNzI3GS7QVuhZJzNGkCvH86IMdMf9NyxeNBEW0HyAbST8LTArbqMtBZlU5HwxhI50JcdmKhudZCZs2k/YipWp8PIz3R+gmSHRtwseV7paM0Np12Q9+xvIYNKto9+frGlPDChP4wTdSpJBN7fY5bcwHrN6v/AFPIHXSIne+8UvKrjlNa8ZFaCMWC8Yc+GBwjCe+dhbV4+UtuDoC1ABgyY3haFXMu8mtWslzbwozzw0W30OFYWg="    
    # Set default python version to avoid repetition later
    - PYTHON_VERSION=3.7
    - MAIN_CMD="pytest"
    - SETUP_CMD="pmda --cov pmda"
    # mdanalysis develop from source (see below), which needs
    # minimal CONDA_MDANALYSIS_DEPENDENCIES
    #- CONDA_DEPENDENCIES="mdanalysis mdanalysistests dask joblib mock codecov cython hypothesis sphinx"
    #- CONDA_MDANALYSIS_DEPENDENCIES="cython mmtf-python six biopython networkx scipy griddataformats gsd hypothesis"
    - CONDA_MDANALYSIS_DEPENDENCIES="mdanalysis mdanalysistests"
    # pin to matplotlib 3.2 should be removed once mda > 1.0.0 is available.
    - CONDA_DEPENDENCIES="${CONDA_MDANALYSIS_DEPENDENCIES} dask distributed joblib mock codecov matplotlib=3.2"
    - CONDA_CHANNELS='conda-forge'
    - CONDA_CHANNEL_PRIORITY=True
    # install development version of MDAnalysis (needed until the test
    # files for analysis.rdf are available in release 0.19.0)
    #- PIP_DEPENDENCIES="git+https://github.com/MDAnalysis/mdanalysis#egg=mdanalysis&subdirectory=package git+https://github.com/MDAnalysis/mdanalysis#egg=mdanalysistests&subdirectory=testsuite"
    - NUMPY_VERSION=stable
    - BUILD_CMD='python setup.py develop'
    - CODECOV=false
    # for automatic doc building & deployment
    - BUILD_DOCS=false
    - GH_DOC_BRANCH: master
    - GH_REPOSITORY: github.com/MDAnalysis/pmda.git
    - GIT_CI_USER: TravisCI
    - GIT_CI_EMAIL: TravisCI@mdanalysis.org
    - MDA_DOCDIR: ${TRAVIS_BUILD_DIR}/build/sphinx/html


  matrix:
    - PYTHON=3.8 CODECOV=true
    - PYTHON=3.7 CODECOV=true
    - PYTHON=3.6 CODECOV=true
    - PYTHON=2.7 CODECOV=true
    - NAME='lint' MAIN_CMD='pylint pmda' BUILD_CMD='' SETUP_CMD=''

matrix:
  fast_finish: true
  include:
    - env: NAME="Doc"
           MAIN_CMD="python setup.py"
           SETUP_CMD="build_sphinx"
           BUILD_DOCS=true
           PIP_DEPENDENCIES="${PIP_DEPENDENCIES} sphinx-sitemap sphinx-rtd-theme"

install:
  - git clone --depth 1 git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh
  - echo $BUILD_CMD
  - $BUILD_CMD

script:
  - echo $MAIN_CMD $SETUP_CMD
  - eval $MAIN_CMD $SETUP_CMD

after_success:
  - |
    if [[ $CODECOV == 'true' ]]; then \
      codecov; \
    fi
  - if [[ ${TRAVIS_PULL_REQUEST} == "false" ]] && [[ ${BUILD_DOCS} == "true" ]] && [[ ${TRAVIS_BRANCH} == ${GH_DOC_BRANCH} ]]; then
            bash ${TRAVIS_BUILD_DIR}/ci/deploy_docs.sh;
    fi
