name: docs deployment
on:
  push:
    branches:
      - master

concurrency:
  group: "${{ github.ref }}-${{ github.head_ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  docs:
    if: "github.repository == 'MDAnalysis/pmda'"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup_miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.7
        auto-update-conda: true
        channel-priority: flexible
        channels: conda-forge
        add-pip-as-python-dependency: true
        mamba-version: "*"

    - name: install package deps
      run: |
        mamba install 'mdanalysis<2' dask distributed sphinx
        pip install sphinx-sitemap sphinx-rtd-theme

    - name: check install
      run: |
        which python
        which pip
        conda info
        conda list

    - name: install package
      run: |
        pip install -v .

    - name: build docs
      run: |
        python setup.py build_sphinx

    - name: deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/sphinx/html
        user_name: 'github-actions'
        user_email: 'github-action@users.noreply.github.com'
